### ISSUE TITLE
(ACCESS) Restart through toil does not always provide the inputs.json

### ISSUE THREAD

**Issue by ionox0** [mskcc/ridgeback#146]
Just making this to keep track of it, as I might be able to circle back and provide a PR with a fix.

We have at least one instance of this error:
```
Traceback (most recent call last):
  File "/juno/home/accessbot/miniconda3/envs/ACCESS_2.0.0/bin/toil-cwl-runner", line 8, in <module>
    sys.exit(main())
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1269, in main
    outobj = toil.restart()
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/common.py", line 828, in restart
    self._cacheAllJobs()
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/common.py", line 1015, in _cacheAllJobs
    self._jobCache = {jobGraph.jobStoreID: jobGraph for jobGraph in self._jobStore.jobs()}
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/common.py", line 1015, in <dictcomp>
    self._jobCache = {jobGraph.jobStoreID: jobGraph for jobGraph in self._jobStore.jobs()}
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 248, in jobs
    yield self.load(self._getJobIdFromDir(os.path.join(tempDir, i)))
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/jobStores/fileJobStore.py", line 208, in load
    job = pickle.load(fileHandle)
EOFError
```

I believe it is because the command to restart does not include the inputs.json file. It should be the last parameter in this command:
```
# LSBATCH: User input
PATH=/juno/home/accessbot/miniconda3/envs/ACCESS_2.0.0/bin:/admin/lsfjuno/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/opt/local/singularity/3.6.2/bin:/juno/work/ci/prod_ridgeback/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin toil-cwl-runner --no-container --logFile toil_log.log --batchSystem lsf --logLevel DEBUG --stats --cleanWorkDir onSuccess --disableCaching --defaultMemory 10G --disableChaining --preserve-environment PATH TMPDIR TOIL_LSF_ARGS SINGULARITY_PULLDIR SINGULARITY_CACHEDIR PWD _JAVA_OPTIONS PYTHONPATH TEMP --jobStore /work/ci/beagle/job-store/9124464e-9f60-4255-af67-3e974d995e42 --tmpdir-prefix /work/ci/beagle/tmp/47c7b1ef-33c0-42d5-b3a4-8adae87aa49e --workDir /work/ci/beagle/work/47c7b1ef-33c0-42d5-b3a4-8adae87aa49e --outdir /work/access/production/runs/voyager/bam_qc/47536afd-32e2-422d-b59f-bd8b712d69cb --restart /work/ci/beagle/work/47c7b1ef-33c0-42d5-b3a4-8adae87aa49e/ACCESS-Pipeline/workflows/ACCESS_pipeline.cwl
```

**Comment by ionox0** [comment]
Here is another example, but in this case a different error is produced:
```
ja04 2021-02-12 13:04:47,840 MainThread INFO toil.leader: Finished toil run with 14 failed jobs.
ja04 2021-02-12 13:04:47,840 MainThread INFO toil.leader: Failed jobs at end of the run: 'CWLGather' kind-CWLGather/instanceZYrJIR 'CWLScatter' kind-CWLScatter/instancetY3HZz 'CWLWorkflow' kind-CWLWorkflow/instanceMZhCvj 'ResolveIndirect' kind-ResolveIndirect/instancepMjtVQ 'CWLGather' kind-CWLGather/instanceRf2v5y 'CWLWorkflow' kind-CWLWorkflow/instanceYmDSan 'CWLScatter' kind-CWLScatter/instanceIgICz8 'CWLGather' kind-CWLGather/instancefMgh3m 'CWLWorkflow' kind-CWLWorkflow/instanceJ_xty_ 'CWLScatter' kind-CWLScatter/instanceneffTX 'file:///work/ci/beagle/work/d1991f9f-7a09-4991-947b-191925ba6552/ACCESS-Pipeline/cwl_tools/expression_tools/group_bams.cwl' kind-file_work_ci_beagle_work_d1991f9f-7a09-4991-947b-191925ba6552_ACCESS-Pipeline_cwl_tools_expression_tools_group_bams.cwl/instance1gJCTr 'ResolveIndirect' kind-ResolveIndirect/instance0UQcCI 'CWLWorkflow' kind-CWLWorkflow/instancebKVVCf 'CWLScatter' kind-CWLScatter/instance0J9P_u
ja04 2021-02-12 13:04:47,845 MainThread DEBUG toil.common: Shutting down batch system ...
ja04 2021-02-12 13:04:47,932 MainThread DEBUG toil.common: Obtained node ID f65c5e64-7f52-4bb8-9484-d34ac493d1ec from file /proc/sys/kernel/random/boot_id
ja04 2021-02-12 13:04:47,933 MainThread DEBUG toil.deferred: Cleaning up deferred functions system
ja04 2021-02-12 13:04:47,934 MainThread DEBUG toil.deferred: Running for file /work/ci/beagle/work/4f08239c-8a4a-4137-89fa-6fcadb12b577/toil-c87ae74c-36d7-480d-8a03-911300a328e3-f65c5e64-7f52-4bb8-9484-d34ac493d1ec/deferred/tmppDdS8p
ja04 2021-02-12 13:04:47,934 MainThread DEBUG toil.deferred: Running orphaned deferred functions
ja04 2021-02-12 13:04:47,934 MainThread DEBUG toil.deferred: Deleting /work/ci/beagle/work/4f08239c-8a4a-4137-89fa-6fcadb12b577/toil-c87ae74c-36d7-480d-8a03-911300a328e3-f65c5e64-7f52-4bb8-9484-d34ac493d1ec/deferred/tmppDdS8p
ja04 2021-02-12 13:04:48,542 Thread-721 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: No activity, sleeping for 1s
ja04 2021-02-12 13:04:48,543 Thread-721 DEBUG toil.batchSystems.abstractGridEngineBatchSystem: Received queue sentinel.
ja04 2021-02-12 13:04:48,543 MainThread DEBUG toil.common: ... finished shutting down the batch system in 0.6973528862 seconds.
Traceback (most recent call last):
  File "/juno/home/accessbot/miniconda3/envs/ACCESS_2.0.0/bin/toil-cwl-runner", line 8, in <module>
    sys.exit(main())
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/cwl/cwltoil.py", line 1269, in main
    outobj = toil.restart()
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/common.py", line 831, in restart
    return self._runMainLoop(rootJobGraph)
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/common.py", line 1072, in _runMainLoop
    jobCache=self._jobCache).run()
  File "/home/accessbot/miniconda3/envs/ACCESS_2.0.0/lib/python2.7/site-packages/toil/leader.py", line 246, in run
    raise FailedJobsException(self.config.jobStore, self.toilState.totalFailedJobs, self.jobStore)
toil.leader.FailedJobsException
```

It looks like the `inputs.json` file is again not provided in the `--restart` command:

```
# LSBATCH: User input
PATH=/juno/home/accessbot/miniconda3/envs/ACCESS_2.0.0/bin:/admin/lsfjuno/lsf/10.1/linux3.10-glibc2.17-x86_64/bin:/opt/local/singularity/3.6.2/bin:/juno/work/ci/prod_ridgeback/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin toil-cwl-runner --no-container --logFile toil_log.log --batchSystem lsf --logLevel DEBUG --stats --cleanWorkDir onSuccess --disableCaching --defaultMemory 10G --disableChaining --preserve-environment PATH TMPDIR TOIL_LSF_ARGS SINGULARITY_PULLDIR SINGULARITY_CACHEDIR PWD _JAVA_OPTIONS PYTHONPATH TEMP --jobStore /work/ci/beagle/job-store/d1991f9f-7a09-4991-947b-191925ba6552 --tmpdir-prefix /work/ci/beagle/tmp/4f08239c-8a4a-4137-89fa-6fcadb12b577 --workDir /work/ci/beagle/work/4f08239c-8a4a-4137-89fa-6fcadb12b577 --outdir /work/access/production/runs/voyager/bam_qc/f6591eee-b53b-4980-b715-21ba797cc71e --restart /work/ci/beagle/work/4f08239c-8a4a-4137-89fa-6fcadb12b577/ACCESS-Pipeline/workflows/ACCESS_pipeline.cwl
```

**Comment by allanbolipata** [comment]
We think this coincided with issues on LSF. Closing for now, but let us know if this happens again.
