### ISSUE TITLE
Fail to get LSF job status

### ISSUE THREAD

**Issue by sivkovic** [mskcc/ridgeback#89]
It looks like this is introduced with #88
`Traceback (most recent call last):
  File "/juno/work/ci/staging_ridgeback/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/juno/work/ci/staging_ridgeback/venv/lib/python3.7/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/srv/services/staging_voyager/ridgeback/toil_orchestrator/tasks.py", line 139, in check_status_of_jobs
    job.message['info'] = lsf_message
TypeError: 'str' object does not support item assignment`

**Comment by nikhil** [comment]
This was related to migrations not being applied properly. Resolved by #94
